# Example configuration for TE-Agents2 simulation
# Copy this file and modify parameters as needed

# Random seed for reproducibility (None for random, integer for fixed)
seed: 42

# Simulation parameters
simulation:
  max_generations: 1000
  carrying_capacity: 1000
  host_start_fitness: 1.0
  host_mutation_rate: 0.01
  host_reproduction_rate: 2
  junk_bp: 1000000  # Genome size in base pairs
  initial_genes: 100
  initial_tes: 50
  save_frequency: 100  # Save checkpoint every N generations

# Gene subtypes with realistic frequencies and properties
genes:
  subtypes:
    ORF:
      length: 1500
      frequency: 0.6  # 60% of genes are protein-coding
      fitness_contribution: 1.0
      mutation_sensitivity: 0.8
      te_insertion_effect: high  # high, medium, low
    promoter:
      length: 200
      frequency: 0.25  # 25% are promoters
      fitness_contribution: 0.3
      mutation_sensitivity: 0.9
      te_insertion_effect: high
    enhancer:
      length: 500
      frequency: 0.15  # 15% are enhancers
      fitness_contribution: 0.5
      mutation_sensitivity: 0.7
      te_insertion_effect: medium

# TE types with autonomous/non-autonomous dynamics
tes:
  types:
    SINE:
      length: 300
      frequency: 0.4  # 40% of TEs are SINEs
      autonomous: false  # Non-autonomous
      parasitizes: [LINE]  # Requires LINEs to transpose
      death_rate: 0.3
      excision_rate: 0.0  # Retrotransposons don't excise
      progeny_distribution: [0.15, 0, 0.55, 1, 0.30, 2]  # [prob, min, prob, max, ...]
    LINE:
      length: 6000
      frequency: 0.3  # 30% are LINEs
      autonomous: true  # Can transpose independently
      parasitizes: []  # No parasitism targets
      death_rate: 0.4
      excision_rate: 0.0
      progeny_distribution: [0.20, 0, 0.50, 1, 0.30, 2]
    LTR:
      length: 8000
      frequency: 0.2  # 20% are LTRs
      autonomous: true
      parasitizes: []
      death_rate: 0.35
      excision_rate: 0.0
      progeny_distribution: [0.25, 0, 0.45, 1, 0.30, 2]
    DNA_TRANSPOSON:
      length: 2000
      frequency: 0.1  # 10% are DNA transposons
      autonomous: true
      parasitizes: []
      death_rate: 0.5
      excision_rate: 0.1  # DNA transposons can excise
      progeny_distribution: [0.30, 0, 0.40, 1, 0.30, 2]

# Performance optimization settings
performance:
  use_parallel: true
  max_workers: 8  # Adjust based on CPU cores
  batch_size: 50
  cache_statistics: true
  use_intervaltree: true
  use_bit_arrays: true
  memory_optimize_freq: 50  # Memory cleanup every N generations
  trace_frequency: 1  # Collect data every N generations
  element_pool_size: 2000
  gene_pool_size: 500
  random_cache_size: 10000
  stats_cache_size: 100
  enable_copy_on_write: true

# Output control - what gets printed during simulation
output:
  splat: false  # Detailed TE jump logging
  splat_fitness: false  # Fitness change logging
  initialization: true  # Setup messages
  generation: true  # Generation progress
  host_extinction: true  # Host extinction events
  te_extinction: true  # TE extinction events
  trial_no: true  # Trial numbering
  gene_init: false  # Gene initialization details
  te_init: false  # TE initialization details
  performance: false  # Performance monitoring

# Logging configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  to_file: false  # Save logs to file
  file_path: ./logs/simulation.log

# Advanced settings
advanced:
  append_gene: false  # Append genes on collision
  terminate_no_tes: false  # Stop if all TEs extinct
  gene_insertion_distribution: triangle  # triangle, flat, uniform
  te_insertion_distribution: triangle
  host_mutation_distribution: triangle
